# Generated by Django 2.0.1 on 2018-02-06 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craft_name', models.CharField(max_length=30)),
                ('craft_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('craft_description', tinymce.models.HTMLField()),
                ('craft_stock', models.PositiveIntegerField(default=10)),
                ('available', models.BooleanField(default=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('craft_image', models.ImageField(blank=True, upload_to='crafts/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='craft.Category')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetterSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
