# Generated by Django 2.0.1 on 2018-02-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='craft',
            old_name='category',
            new_name='categories',
        ),
    ]
