# Generated by Django 2.0.1 on 2018-01-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
