# Generated by Django 2.0.1 on 2018-01-11 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0002_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craft_name', models.CharField(max_length=30)),
                ('craft_price', models.CharField(max_length=10)),
                ('craft_description', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craft.Artist')),
                ('category', models.ManyToManyField(to='craft.categories')),
            ],
        ),
    ]
