# Generated by Django 2.0.1 on 2018-01-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0003_craft'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='craft_image',
            field=models.ImageField(blank=True, upload_to='crafts/'),
        ),
    ]
