# Generated by Django 2.0.1 on 2018-01-17 16:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0006_auto_20180117_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craft',
            name='craft_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
