# Generated by Django 2.0.1 on 2018-01-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0007_auto_20180117_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='craft',
            name='craft_slug',
            field=models.SlugField(default=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='craft',
            name='craft_stock',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.RemoveField(
            model_name='craft',
            name='category',
        ),
        migrations.AddField(
            model_name='craft',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='craft.categories'),
        ),
        migrations.AlterField(
            model_name='craft',
            name='craft_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
