# Generated by Django 2.0.1 on 2018-02-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0010_auto_20180125_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
